export default function TermsPage() {
  return (
    <div style={{
      padding: "24px 20px 60px",
      fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', sans-serif",
      maxWidth: 680,
    }}>
      <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 28 }}>
        <a href="/m/legal" style={{
          width: 40, height: 40, borderRadius: 12,
          background: "#111827", border: "1px solid #1e293b",
          display: "flex", alignItems: "center", justifyContent: "center",
          textDecoration: "none", color: "#94a3b8", fontSize: 20, flexShrink: 0,
        }}>←</a>
        <div>
          <div style={{ fontSize: 26, fontWeight: 800, color: "#f8fafc" }}>Terms of Service</div>
          <div style={{ fontSize: 14, color: "#475569", marginTop: 2 }}>Last updated: July 2026</div>
        </div>
      </div>

      <LegalSection title="1. About this app">
        This application (&quot;the App&quot;) is a personal AI-powered training assistant that generates
        weekly structured training plans for cyclists and runners. It connects to Zwift and
        Intervals.icu on your behalf to read ride data and push workouts to your calendar.
      </LegalSection>

      <LegalSection title="2. Who may use it">
        The App is currently in private beta and intended for personal, non-commercial use only.
        You must be at least 16 years old to use it. By using the App you confirm you have no
        medical condition that would make structured training dangerous without physician supervision.
      </LegalSection>

      <LegalSection title="3. AI-generated training plans">
        Training plans are generated by an AI model (OpenAI) based on your Zwift ride history
        and the profile you provide. These plans are informational and do not constitute
        medical or professional coaching advice. Always use good judgment — if a workout feels
        dangerous or you are unwell, stop and seek medical guidance.
      </LegalSection>

      <LegalSection title="4. Third-party services">
        The App integrates with Zwift and Intervals.icu. Your use of those platforms is governed
        by their own Terms of Service. We access your data on those platforms only with credentials
        you provide, and solely for the purpose of generating and syncing your training plan.
        We are not affiliated with Zwift Labs or Intervals.icu.
      </LegalSection>

      <LegalSection title="5. Your credentials">
        Your Zwift email and password are transmitted directly to Zwift&apos;s servers and are never
        stored by this application. Your Intervals.icu API key is stored securely and used only
        to push workouts and read activity data. You may revoke access at any time by
        disconnecting in the Profile tab.
      </LegalSection>

      <LegalSection title="6. No warranties">
        The App is provided &quot;as is&quot; without any warranty, express or implied. We do not
        guarantee that generated training plans will improve your performance, prevent injury,
        or be free of errors. Training metrics (TSS, CTL, ATL, IF) are estimates based on
        the industry-standard PMC model and may not perfectly reflect your actual physiological state.
      </LegalSection>

      <LegalSection title="7. Limitation of liability">
        To the fullest extent permitted by law, the developers of this App shall not be liable
        for any injury, loss, or damage arising from use of AI-generated training plans,
        inaccurate fitness data, or any failure of third-party integrations.
      </LegalSection>

      <LegalSection title="8. Changes to these terms">
        We may update these terms at any time. Continued use of the App after changes constitutes
        acceptance of the new terms. Material changes will be noted in the app.
      </LegalSection>

      <LegalSection title="9. Contact">
        For questions about these terms, contact us at{" "}
        <a href="mailto:support@voltiq.ai" style={{ color: "#3b82f6" }}>support@voltiq.ai</a>.
      </LegalSection>
    </div>
  );
}

function LegalSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 24 }}>
      <div style={{
        fontSize: 16, fontWeight: 700, color: "#94a3b8",
        marginBottom: 8, letterSpacing: ".2px",
      }}>
        {title}
      </div>
      <div style={{
        fontSize: 15, color: "#475569", lineHeight: 1.75,
        background: "#0f172a", borderRadius: 12,
        padding: "14px 16px", border: "1px solid #1e293b",
      }}>
        {children}
      </div>
    </div>
  );
}
