import Link from "next/link";

export const metadata = { title: "Terms of Use — Zwift AI Dashboard" };

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 760, margin: "0 auto", padding: "48px 24px 80px", fontFamily: "Inter, -apple-system, sans-serif", color: "#14171a", lineHeight: 1.8 }}>
      <div style={{ marginBottom: 32 }}>
        <Link href="/dashboard" style={{ fontSize: 13, color: "#2f8fe0", textDecoration: "none" }}>← Back to dashboard</Link>
      </div>

      <h1 style={{ fontSize: 28, fontWeight: 800, marginBottom: 6, letterSpacing: "-0.5px" }}>Terms of Use</h1>
      <p style={{ fontSize: 13, color: "#5b6168", marginBottom: 40 }}>Last updated: July 2026</p>

      <Section title="Acceptance of terms">
        By accessing and using this dashboard you agree to be bound by these Terms of Use. If you do not agree, please
        stop using the service immediately. These terms may be updated at any time without notice.
      </Section>

      <Section title="Permitted use">
        This tool is provided for personal, non-commercial use only. You may use it to view your own Zwift ride data
        and receive AI-generated training suggestions. You may not:
        <ul style={{ marginTop: 10, paddingLeft: 20 }}>
          <li>Resell, sublicense, or commercially exploit this service</li>
          <li>Attempt to reverse-engineer, scrape, or automate access beyond normal use</li>
          <li>Use this service to access another person&apos;s Zwift account without their explicit consent</li>
          <li>Circumvent any security or authentication measures</li>
        </ul>
      </Section>

      <Section title="Your Zwift credentials">
        You authenticate directly with Zwift&apos;s own login system. Your Zwift username and password are never sent
        to or stored by this service. An encrypted session token is stored in a secure browser cookie solely to
        maintain your logged-in state. You are responsible for the security of your Zwift account credentials.
      </Section>

      <Section title="AI-generated content">
        Training plans and insights are generated by a third-party AI (OpenAI). This content is experimental and
        automatically produced. You acknowledge that AI output may be inaccurate, inappropriate for your fitness
        level, or otherwise unsuitable. You should apply your own judgement — and consult a coach or physician —
        before acting on any AI recommendation.
      </Section>

      <Section title="Service availability">
        This service is provided &quot;as is&quot; and &quot;as available&quot; without any warranty of continuous
        availability. The service may be interrupted, modified, or discontinued at any time without notice and without
        liability to you.
      </Section>

      <Section title="Limitation of liability">
        To the fullest extent permitted by law, the operator of this service shall not be liable for any damages of
        any kind arising from your use of, or inability to use, this service — including but not limited to physical
        injury, data loss, or financial loss. See the full{" "}
        <Link href="/legal/disclaimer" style={{ color: "#2f8fe0" }}>Disclaimer</Link> for details.
      </Section>

      <Section title="Governing law">
        These terms are governed by and construed in accordance with the laws of the State of Israel. Any dispute
        arising under these terms shall be subject to the exclusive jurisdiction of the competent courts of Israel.
      </Section>

      <div style={{ borderTop: "1px solid #e5e7eb", paddingTop: 24, marginTop: 40, fontSize: 12.5, color: "#5b6168" }}>
        Also see: <Link href="/legal/disclaimer" style={{ color: "#2f8fe0" }}>Disclaimer</Link>
        {" · "}
        <Link href="/legal/privacy" style={{ color: "#2f8fe0" }}>Privacy Policy</Link>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 36 }}>
      <h2 style={{ fontSize: 16, fontWeight: 700, marginBottom: 10, color: "#14171a" }}>{title}</h2>
      <div style={{ fontSize: 14, color: "#374151" }}>{children}</div>
    </div>
  );
}
