import Link from "next/link";

export const metadata = { title: "Disclaimer — Zwift AI Dashboard" };

export default function DisclaimerPage() {
  return (
    <div style={{ maxWidth: 760, margin: "0 auto", padding: "48px 24px 80px", fontFamily: "Inter, -apple-system, sans-serif", color: "#14171a", lineHeight: 1.8 }}>
      <div style={{ marginBottom: 32 }}>
        <Link href="/dashboard" style={{ fontSize: 13, color: "#2f8fe0", textDecoration: "none" }}>← Back to dashboard</Link>
      </div>

      <h1 style={{ fontSize: 28, fontWeight: 800, marginBottom: 6, letterSpacing: "-0.5px" }}>Disclaimer</h1>
      <p style={{ fontSize: 13, color: "#5b6168", marginBottom: 40 }}>Last updated: July 2026</p>

      <Section title="Independent tool — not affiliated with Zwift">
        This dashboard is an independent, personal project and is in no way affiliated with, sponsored by, endorsed by,
        or otherwise connected to Zwift, Inc. or any of its subsidiaries. The Zwift name and logo are trademarks of
        Zwift, Inc. and are referenced here solely for descriptive identification purposes.
      </Section>

      <Section title="Not medical or clinical advice">
        All content displayed on this dashboard — including training plans, performance insights, heart-rate analysis,
        fatigue alerts, and AI-generated recommendations — is provided for <strong>informational and entertainment
        purposes only</strong>. Nothing on this site constitutes medical advice, clinical guidance, diagnosis, or
        treatment of any kind.
        <br /><br />
        Heart-rate anomaly alerts are generated by an automated algorithm that compares recent ride data to your
        historical baseline. These alerts <strong>may be inaccurate</strong>, may miss real conditions, and may fire
        without cause. They are not a substitute for professional medical evaluation.
        <br /><br />
        <strong>Always consult a qualified physician, cardiologist, or certified sports-medicine professional</strong>{" "}
        before changing your training volume, intensity, or frequency — particularly if you have any pre-existing
        cardiovascular condition, chronic illness, or injury.
      </Section>

      <Section title="No guarantee of accuracy">
        Training metrics, power estimates, fitness scores, and AI-generated plans are computed from data provided by
        Zwift's unofficial API and may contain errors, gaps, or outdated values. The AI model may produce inaccurate,
        incomplete, or inappropriate recommendations. We make no warranty, express or implied, as to the accuracy,
        reliability, or fitness for purpose of any information displayed.
      </Section>

      <Section title="Limitation of liability">
        To the fullest extent permitted by applicable law, the creator of this tool accepts <strong>no liability
        whatsoever</strong> for any direct, indirect, incidental, special, or consequential loss or damage of any kind
        arising from:
        <ul style={{ marginTop: 10, paddingLeft: 20 }}>
          <li>Reliance on any training recommendation, alert, or insight displayed here</li>
          <li>Physical injury, illness, or health consequence sustained during or after training</li>
          <li>Errors, interruptions, or data loss affecting the service</li>
          <li>Unauthorised access to your Zwift credentials or account</li>
        </ul>
        You use this tool <strong>entirely at your own risk</strong>.
      </Section>

      <Section title="Third-party services">
        This dashboard uses OpenAI's API to generate training content. AI-generated text is not reviewed by a human
        before being displayed. The accuracy and appropriateness of AI output cannot be guaranteed.
      </Section>

      <div style={{ borderTop: "1px solid #e5e7eb", paddingTop: 24, marginTop: 40, fontSize: 12.5, color: "#5b6168" }}>
        Also see: <Link href="/legal/terms" style={{ color: "#2f8fe0" }}>Terms of Use</Link>
        {" · "}
        <Link href="/legal/privacy" style={{ color: "#2f8fe0" }}>Privacy Policy</Link>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 36 }}>
      <h2 style={{ fontSize: 16, fontWeight: 700, marginBottom: 10, color: "#14171a" }}>{title}</h2>
      <div style={{ fontSize: 14, color: "#374151" }}>{children}</div>
    </div>
  );
}
