import Link from "next/link";

export default function DashboardFooter() {
  const year = new Date().getFullYear();

  return (
    <footer
      style={{
        marginTop: 0,
        borderTop: "3px solid var(--accent)",
        background: "var(--accent-2)",
        color: "rgba(255,255,255,0.55)",
        fontSize: 12.5,
      }}
    >
      <div
        style={{
          maxWidth: 960,
          margin: "0 auto",
          padding: "28px 24px",
          display: "grid",
          gridTemplateColumns: "1fr auto 1fr",
          gap: 24,
          alignItems: "start",
        }}
      >
        {/* Left - brand */}
        <div>
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
            <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
              <path d="M11 2L4 10h5l-2 6 9-9h-5l2-7z" fill="currentColor" />
            </svg>
            <span style={{ color: "rgba(255,255,255,0.9)", fontWeight: 700, fontSize: 14 }}>
              Zwift Dashboard
            </span>
          </div>
          <div style={{ lineHeight: 1.6 }}>
            AI-powered training plans and performance insights, built for Zwift riders.
          </div>
          <div style={{ marginTop: 10, color: "rgba(255,255,255,0.3)", fontSize: 11 }}>
            {"©"} {year} {"·"} Not affiliated with Zwift, Inc.
          </div>
        </div>

        {/* Centre - nav */}
        <nav style={{ display: "flex", flexDirection: "column", gap: 10, alignItems: "center" }}>
          <Link href="/dashboard#weekly-plan" className="footer-nav-link">Weekly plan</Link>
          <Link href="/dashboard#ai-insights" className="footer-nav-link">AI Insights</Link>
          <Link href="/dashboard/diagnostics" className="footer-nav-link">Diagnostics</Link>
        </nav>

        {/* Right - data note */}
        <div style={{ textAlign: "right", lineHeight: 1.6 }}>
          <div style={{ color: "rgba(255,255,255,0.9)", fontWeight: 600, fontSize: 12, marginBottom: 6 }}>
            About your data
          </div>
          All ride data is fetched live from your Zwift account and never stored on our servers.
          Training plans are generated by AI and stored only in your own browser.
        </div>
      </div>
    </footer>
  );
}
