import Link from "next/link";

// A clean, on-brand footer for the dashboard: dark band matching the
// header colour (--accent-2 / #14171a), orange accent line on top,
// three columns - brand/tagline, navigation links, data note.
export default function DashboardFooter() {
  const year = new Date().getFullYear();

  return (
    <footer
      style={{
        marginTop: 48,
        borderTop: "3px solid var(--accent)",
        background: "var(--accent-2)",
        color: "rgba(255,255,255,0.55)",
        fontSize: 12.5,
      }}
    >
      <div
        style={{
          maxWidth: 960,
          margin: "0 auto",
          padding: "28px 24px",
          display: "grid",
          gridTemplateColumns: "1fr auto 1fr",
          gap: 24,
          alignItems: "start",
        }}
      >
        {/* Left - brand */}
        <div>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 8,
              marginBottom: 8,
            }}
          >
            {/* Zwift-orange bolt mark */}
            <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
              <path d="M11 2L4 10h5l-2 6 9-9h-5l2-7z" fill="#ff6600" />
            </svg>
            <span
              style={{
                color: "rgba(255,255,255,0.9)",
                fontWeight: 700,
                fontSize: 14,
                letterSpacing: "0.01em",
              }}
            >
              Zwift Dashboard
            </span>
          </div>
          <div style={{ lineHeight: 1.6 }}>
            AI-powered training plans and performance insights, built for Zwift
            riders.
          </div>
          <div style={{ marginTop: 10, color: "rgba(255,255,255,0.3)", fontSize: 11 }}>
            © {year} · Not affiliated with Zwift, Inc.
          </div>
        </div>

        {/* Centre - nav links */}
        <nav
          style={{
            display: "flex",
            flexDirection: "column",
            gap: 10,
            alignItems: "center",
          }}
        >
          {[
            { href: "/dashboard#weekly-plan", label: "Weekly plan" },
            { href: "/dashboard#ai-insights", label: "AI Insights" },
            { href: "/dashboard/diagnostics", label: "Diagnostics" },
          ].map(({ href, label }) => (
            <Link
              key={href}
              href={href}
              style={{
                color: "rgba(255,255,255,0.65)",
                textDecoration: "none",
                transition: "color 0.15s",
              }}
              onMouseEnter={(e) =>
                ((e.target as HTMLAnchorElement).style.color = "#ff6600")
              }
              onMouseLeave={(e) =>
                ((e.target as HTMLAnchorElement).style.color =
                  "rgba(255,255,255,0.65)")
              }
            >
              {label}
            </Link>
          ))}
        </nav>

        {/* Right - data note */}
        <div style={{ textAlign: "right", lineHeight: 1.6 }}>
          <div
            style={{
              color: "rgba(255,255,255,0.9)",
              fontWeight: 600,
              fontSize: 12,
              marginBottom: 6,
            }}
          >
            About your data
          </div>
          All ride data is fetched live from your Zwift account and never stored
          on our servers. Training plans are generated by AI and stored only in
          your own browser.
        </div>
      </div>
    </footer>
  );
}
